version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: vesica/php72
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build-production:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Production Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Production Docker image
          command: docker save -o prod.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./prod.tar
  publish-production:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/prod.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="ci${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
  build-dev:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Production Docker image
          command: docker build -f Dockerfile.dev -t $IMAGE_NAME:dev .
      - run:
          name: Archive Production Docker image
          command: docker save -o dev.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./dev.tar
  publish-dev:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/dev.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:dev

#  publish-tag:
#    executor: docker-publisher
#    steps:
#      - attach_workspace:
#          at: /tmp/workspace
#      - setup_remote_docker
#      - run:
#          name: Load archived Docker image
#          command: docker load -i /tmp/workspace/image.tar
#      - run:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#            IMAGE_TAG=${CIRCLE_TAG}
#            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
#            docker push $IMAGE_NAME:latest
#            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  production:
    jobs:
      - build-production:
          filters:
            branches:
              only: master
      - publish-production:
          context: Docker Hub
          requires:
            - build-production
          filters:
            branches:
              only: master
  dev:
    jobs:
      - build-dev:
          filters:
            branches:
              only: master
      - publish-dev:
          context: Docker Hub
          requires:
            - build-dev
          filters:
            branches:
              only: master
#  build-tags:
#    jobs:
#      - build:
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/
#      - publish-tag:
#          context: Docker Hub
#          requires:
#            - build
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/